name: Update README with user count

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script and update stats
        id: get_count
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          node userCount.js
          COUNT=$(jq '.data[-1].count' user-stats.json)
          echo "count=$COUNT" >> $GITHUB_OUTPUT
          echo "✔ Count: $COUNT"

      - name: Generate chart URL
        id: chart
        run: |
          LABELS=$(jq -c '[.data[].date]' user-stats.json)
          COUNTS=$(jq -c '[.data[].count]' user-stats.json)

          CONFIG=$(jq -n \
            --argjson labels "$LABELS" \
            --argjson data "$COUNTS" \
            '{type:"line",data:{labels:$labels,datasets:[{label:"Users",data:$data}]}}')

          URL="https://quickchart.io/chart?c=$(node -e "console.log(encodeURIComponent(process.argv[1]))" "$CONFIG")"

          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "✔ Chart URL: $URL"

      - name: Update README.md
        run: |
          sed -i "s|<USER_COUNT_PLACEHOLDER>|${{ steps.get_count.outputs.count }}|" README.md
          sed -i "s|https://quickchart.io/chart?.*|${{ steps.chart.outputs.url }}|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update user count to ${{ steps.get_count.outputs.count }}" || echo "No changes"
          git push
