name: Update README with user count

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script and get count, update user-stats.json
        id: get_count
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          # Получаем count из Node.js скрипта
          COUNT=$(node userCount.js)
          echo "✔ Count from DB: $COUNT"

          STATS_FILE=user-stats.json
          TODAY=$(date +'%Y-%m-%d')

          # Создаём файл, если его нет
          if [ ! -f "$STATS_FILE" ]; then
            echo "[]" > "$STATS_FILE"
            echo "✔ Created empty $STATS_FILE"
          fi

          # Обновляем или добавляем запись с сегодняшней датой
          UPDATED_JSON=$(jq --arg date "$TODAY" --argjson count "$COUNT" '
            (map(select(.date == $date)) | length) as $exists
            | if $exists > 0 then
                map(if .date == $date then .count = $count else . end)
              else
                . + [{date: $date, count: $count}]
              end
          ' "$STATS_FILE")

          echo "$UPDATED_JSON" > "$STATS_FILE"
          echo "✔ Updated $STATS_FILE with today's count"

          # Передаём count в output для следующих шагов
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Log value
        run: |
          echo "✔ User count is: ${{ steps.get_count.outputs.count }}"

      - name: Update README.md
        run: sed -i "s/<USER_COUNT_PLACEHOLDER>/${{ steps.get_count.outputs.count }}/" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update user count to ${{ steps.get_count.outputs.count }}" || echo "No changes"
          git push
